// Flat config, because `next lint` was removed in Next.js 16. The bare
// `next lint` we used to run was parsed as `next <dir>` and died with
// "no such directory: <repo>/lint" — a script that fails for a reason that has
// nothing to do with the code trains people to ignore lint entirely.
//
// Generated by `npx @next/codemod@canary next-lint-to-eslint-cli .` and then
// commented.
//
// NOTE ON THE TYPESCRIPT VERSION: `eslint-config-next` loads
// `typescript-eslint`, which reads the TypeScript compiler API at import time
// and throws outright on TypeScript >= 7 (see typescript-eslint#10940). No
// published typescript-eslint supports it yet — its peer range is still
// `<6.1.0`. So `typescript` is pinned to ^6.0.3 in package.json; on ^7 this
// config cannot even be loaded, and lint is dead again. Revisit when
// typescript-eslint ships TS 7 support.
import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypescript from "eslint-config-next/typescript";

const eslintConfig = [
  ...nextCoreWebVitals,
  ...nextTypescript,
  {
    // `eslint .` walks the whole tree, so everything .gitignore keeps out of
    // the repo has to be listed here too, and the build-output patterns have to
    // match at any depth rather than only at the root. Two ways this bites:
    //
    //   - Without `**/dist/**`, a `npm run build:kernel` followed by
    //     `npm run lint` reports every warning twice — once for the source and
    //     once for its own emitted JavaScript, where it is unfixable.
    //   - Without `.claude/**`, lint descends into the agent worktrees kept
    //     there. Each one is a full checkout of this repo WITH its own `.next`,
    //     so a single stale worktree turned 22 real problems into 38,846 and
    //     buried the ones in src/. Flat config does not skip dot-directories on
    //     its own the way .eslintrc did.
    ignores: [
      "**/node_modules/**",
      "**/.next/**",
      "**/dist/**",
      "**/out/**",
      "**/build/**",
      "**/coverage/**",
      ".claude/**",
      ".vercel/**",
      ".serena/**",
      "artifacts/**",
      "data/runs/**",
      // Throwaway feasibility-spike code. Deliberately outside the production
      // tsconfig `include` too, so it is typechecked and linted by nothing —
      // the trade a spike is allowed to make and production code is not. If
      // anything here graduates into src/, it gets linted like everything else.
      "experiments/**",
      "next-env.d.ts",
    ],
  },
  {
    // After the two `next` spreads, not before them: a flat config is applied in
    // order and the later block wins. Written above them this would be silently
    // overridden and the tree would look exactly the same, which is the failure
    // mode worth naming because nothing about it looks wrong.
    //
    // A leading underscore is already how this codebase says "this binding
    // exists because the signature or the destructuring requires it, not
    // because anything reads it". `withoutSecret` is the clearest case: the
    // whole purpose of `const { passwordHash: _passwordHash, ...rest }` is to
    // *drop* the hash, and a rule that cannot see the convention reports the
    // codebase doing precisely the right thing. Eight of the fourteen warnings
    // this replaces were that.
    //
    // Severity stays `warn`. `--max-warnings 0` in the `lint` script is what
    // makes it fail, so an editor shows these as warnings while CI still
    // refuses them — and the flag lives in the script rather than in `ci.yml`
    // and `localci.yml` separately, because localci exists to mirror CI and two
    // copies of one threshold is how they stop matching.
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
          destructuredArrayIgnorePattern: "^_",
          // `...rest` is the idiom that drops a field; the sibling it leaves
          // behind is the point, not an oversight.
          ignoreRestSiblings: true,
        },
      ],
    },
  },
];

export default eslintConfig;
