// Flat config, because `next lint` was removed in Next.js 16. The bare
// `next lint` we used to run was parsed as `next <dir>` and died with
// "no such directory: <repo>/lint" — a script that fails for a reason that has
// nothing to do with the code trains people to ignore lint entirely.
//
// Generated by `npx @next/codemod@canary next-lint-to-eslint-cli .` and then
// commented.
//
// NOTE ON THE TYPESCRIPT VERSION: `eslint-config-next` loads
// `typescript-eslint`, which reads the TypeScript compiler API at import time
// and throws outright on TypeScript >= 7 (see typescript-eslint#10940). No
// published typescript-eslint supports it yet — its peer range is still
// `<6.1.0`. So `typescript` is pinned to ^6.0.3 in package.json; on ^7 this
// config cannot even be loaded, and lint is dead again. Revisit when
// typescript-eslint ships TS 7 support.
import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypescript from "eslint-config-next/typescript";

const eslintConfig = [
  ...nextCoreWebVitals,
  ...nextTypescript,
  {
    // `eslint .` walks the whole tree, so everything .gitignore keeps out of
    // the repo has to be listed here too. Without `dist/**` a plain
    // `npm run build:kernel` followed by `npm run lint` reports the same
    // warnings twice — once for the source and once for its own emitted
    // JavaScript — and the second copy is unfixable.
    ignores: [
      "node_modules/**",
      ".next/**",
      "out/**",
      "build/**",
      "dist/**",
      "coverage/**",
      ".vercel/**",
      "artifacts/**",
      "data/runs/**",
      "next-env.d.ts",
    ],
  },
];

export default eslintConfig;
